name: Python code quality

on:
  push:
    branches: [ main ]
    paths:
      - '**.py'

  pull_request:
    branches: [ main ]
    paths:
      - '**.py'

  workflow_dispatch:

permissions:
  contents: read

jobs:
  checks-format-and-lint:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        - name: Set up Python 3
          uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
          with:
            python-version: "3.12"
            cache: 'pip'
        - name: Install dependencies
          run: |
            python3 -m pip install --upgrade pip
            python3 -m pip install ruff
        - name: Lint with ruff
          run: ruff check .
        - name: Check formatting with ruff
          run: ruff format . --check
